# This vLLM Dockerfile is used to construct image that can build and run vLLM on Sophon TPU platform with RISC-V.

# base images
FROM ubuntu:24.04 AS base

# set env
ENV DEBIAN_FRONTEND=noninteractive \
    PYTHON_VERSION=3.12 \
    PATH="/root/.local/bin:/root/.cargo/bin:/workspace/.venv/bin:${PATH}" \
    VIRTUAL_ENV=/workspace/.venv

WORKDIR /workspace

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        curl \
        git \
        python3-dev \
        python3-setuptools \
        python3-pip \
        python${PYTHON_VERSION} \
        python${PYTHON_VERSION}-venv \
        vim \
        pandoc \
        wget \
        gnupg \
        numactl \
        gcc-12 \
        g++-12 \
        libtcmalloc-minimal4 \
        libnuma-dev \
        ffmpeg \
        libsm6 \
        libxext6 \
        libgl1 \
        libjpeg-dev \
        libopenjp2-7-dev \
        libtiff-dev \
        zlib1g-dev \
        libfreetype6-dev \
        liblcms2-dev \
        libwebp-dev \
        ninja-build \
        pkg-config \
        gfortran \
        libopenblas-dev \
        liblapack-dev \
        libatlas-base-dev \
        libharfbuzz-dev \
        libfribidi-dev \
        libxcb1-dev && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 --slave /usr/bin/g++ g++ /usr/bin/g++-12 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 安装所有必要的系统依赖
RUN apt-get update && apt-get install -y \
    libprotobuf-dev \
    protobuf-compiler \
    libprotoc-dev \
    libssl-dev \
    llvm-20-dev \
    llvm-20-tools \
    llvm-20 \
    clang \
    patchelf \
    cmake \
    && rm -rf /var/lib/apt/lists/*

ENV LLVM_CONFIG=/usr/lib/llvm-20/bin/llvm-config
ENV PATH="/usr/lib/llvm-20/bin:$PATH"

# install uv and Rust
RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# create Python virtual environment
RUN uv venv -p python${PYTHON_VERSION} /workspace/.venv && \
    uv pip install pip setuptools

COPY third-party third-party
COPY third-party/ld-linux-riscv* /lib/
RUN cd third-party \
 && tar -xzvf torch-tpu*.tar.gz \
 && uv pip install ./torch-*_riscv64.whl ./dist/torch_tpu*_riscv64.whl \
 && rm -rf *
ENV LD_LIBRARY_PATH=/workspace/.venv/lib/python3.12/site-packages/torch/lib


# install Python dependencies
COPY requirements-common.txt requirements-common.txt
COPY requirements-sophtpu.txt requirements-sophtpu.txt
RUN uv pip install --no-cache -r requirements-sophtpu.txt && \
    uv pip install --no-cache setuptools_scm aiohttp uvloop fastapi uvicorn partial_json_parser \
                              python-multipart pytest setuptools_rust maturin scikit-build meson \
                              cython pythran pybind11 scikit-build-core nanobind && \
    rm requirements-*.txt

RUN git clone https://github.com/mesonbuild/meson-python.git /tmp/meson-python \
    && cd /tmp/meson-python \
    && uv pip install . \
    && rm -rf /tmp/meson-python

RUN git clone --branch v0.11.0 https://github.com/vllm-project/vllm.git \
 && cd vllm \
 && python3 use_existing_torch.py \
 && uv pip install -r ./requirements/build.txt \
 && VLLM_TARGET_DEVICE=empty uv pip install -e . --no-build-isolation

COPY vllm_sophon /workspace/vllm_sophon
WORKDIR /workspace/vllm_sophon
RUN uv pip install -e . --no-build-isolation

# clean up
RUN rm -rf /root/.cache/* /tmp/*

WORKDIR /workspace/


# git clone https://github.com/mesonbuild/meson-python.git
# cd meson-python
# uv pip install .
