# This vLLM Dockerfile is used to construct image that can build and run vLLM on Sophon TPU platform.

FROM ubuntu:22.04 AS base

ENV CCACHE_DIR=/root/.cache/ccache
ENV CMAKE_CXX_COMPILER_LAUNCHER=ccache
ENV DEBIAN_FRONTEND=noninteractive

# Install development tools and dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends curl pandoc ca-certificates vim \
    && apt-get auto-remove \
    && rm -rf /var/lib/apt/lists/*

# Python related
ENV VIRTUAL_ENV=/usr/src/.venv/ \
    PATH=$PATH:/usr/src/.venv/bin/:/root/.local/bin/ \
    LD_LIBRARY_PATH=/root/.local/share/uv/python/cpython-3.11.11-linux-x86_64-gnu/lib/

# Script to install uv & create python venv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh \
    && uv python install 3.11 \
    && uv venv /usr/src/.venv

RUN apt-get update -y \
    && apt-get install -y wget numactl gcc-12 g++-12 libtcmalloc-minimal4 libnuma-dev \
    && apt-get install -y ffmpeg libsm6 libxext6 libgl1 \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 --slave /usr/bin/g++ g++ /usr/bin/g++-12 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace/vllm

COPY requirements-common.txt requirements-common.txt
COPY requirements-sophtpu.txt requirements-sophtpu.txt
RUN uv pip install --system -r requirements-sophtpu.txt \
    && uv pip install --system setuptools_scm \
    && uv pip install --system torch==2.1.0 --index-url https://download.pytorch.org/whl/cpu --force-reinstall

COPY . .
#RUN --mount=type=cache,target=/root/.cache/pip \
#    --mount=type=cache,target=/root/.cache/ccache \
#    --mount=type=bind,source=.git,target=.git \
#    VLLM_TARGET_DEVICE=empty python3 setup.py develop

WORKDIR /workspace/
#RUN ln -s /workspace/vllm/tests && ln -s /workspace/vllm/examples && ln -s /workspace/vllm/benchmarks

# install development dependencies (for testing)
#RUN --mount=type=cache,target=/root/.cache/pip \
#    pip install -e tests/vllm_test_utils

#ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server"]
