# This vLLM Dockerfile is used to construct image that can build and run vLLM on Sophon TPU platform with RISC-V.

# base images
FROM ubuntu:24.04 AS base

# set env
ENV DEBIAN_FRONTEND=noninteractive \
    PYTHON_VERSION=3.12 \
    PATH="/root/.local/bin:/root/.cargo/bin:/workspace/.venv/bin:${PATH}" \
    VIRTUAL_ENV=/workspace/.venv

WORKDIR /workspace

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        curl \
        git \
        python3-dev \
        python3-setuptools \
        python3-pip \
        python${PYTHON_VERSION} \
        python${PYTHON_VERSION}-venv \
        vim \
        pandoc \
        wget \
        numactl \
        gcc-12 \
        g++-12 \
        libtcmalloc-minimal4 \
        libnuma-dev \
        ffmpeg \
        libsm6 \
        libxext6 \
        libgl1 \
        libjpeg-dev \
        libopenjp2-7-dev \
        libtiff-dev \
        zlib1g-dev \
        libfreetype6-dev \
        liblcms2-dev \
        libwebp-dev \
        libharfbuzz-dev \
        libfribidi-dev \
        libxcb1-dev && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 --slave /usr/bin/g++ g++ /usr/bin/g++-12 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# install uv and Rust
RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# create Python virtual environment
RUN uv venv -p python${PYTHON_VERSION} /workspace/.venv && \
    uv pip install pip setuptools

# install Python dependencies
COPY requirements-common.txt requirements-common.txt
COPY requirements-sophtpu.txt requirements-sophtpu.txt
RUN uv pip install --no-cache -r requirements-sophtpu.txt && \
    uv pip install --no-cache setuptools_scm aiohttp uvloop fastapi uvicorn partial_json_parser python-multipart && \
    rm requirements-*.txt

# copy vllm code
COPY vllm /workspace/vllm
COPY tests/models/decoder_only/language/test_whole_model.py /workspace

# clean up
RUN rm -rf /root/.cache/* /tmp/*

WORKDIR /workspace/